version: '2.3'
services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_DEFAULT_EMAIL: root
    volumes:
      - ./postgresql/scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-P", "root", "-U", "root" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  am-analytics:
    image: wso2/wso2am-analytics-worker:2.6.0
    ports:
      - "9091:9091"
      - "9444:9444"
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9091"]
      interval: 30s
      timeout: 120s
      start_period: 80s
      retries: 10
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apim-analytics:/home/wso2carbon/wso2-config-volume
  is-as-km:
    image: wso2/wso2is-km:5.7.0
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9443"]
      interval: 40s
      timeout: 120s
      start_period: 100s
      retries: 15
    depends_on:
      postgres:
        condition: service_healthy
      am-analytics:
        condition: service_healthy
    volumes:
      - ./is-as-km:/home/wso2carbon/wso2-config-volume
    ports:
      - "9765:9763"
      - "9445:9443"
  api-manager:
    image: wso2/wso2am:2.6.0
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9443"]
      interval: 50s
      timeout: 120s
      start_period: 100s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      am-analytics:
        condition: service_healthy
      is-as-km:
        condition: service_healthy
    volumes:
      - ./apim:/home/wso2carbon/wso2-config-volume
    ports:
      - "9763:9763"
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
